"""Agent led onboarding fields

Revision ID: 00c683dbac3d
Revises: f1670ce23c6f
Create Date: 2026-03-01 02:21:26.061879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00c683dbac3d'
down_revision: Union[str, Sequence[str], None] = 'f1670ce23c6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shops', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.add_column('shops', sa.Column('onboarded_by_agent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'shops', 'users', ['onboarded_by_agent_id'], ['id'])
    op.create_foreign_key(None, 'shops', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shops', type_='foreignkey')
    op.drop_constraint(None, 'shops', type_='foreignkey')
    op.drop_column('shops', 'onboarded_by_agent_id')
    op.drop_column('shops', 'owner_id')
    # ### end Alembic commands ###
