"""add_hashed_pin_to_shops

Revision ID: 11b232c80aca
Revises: 36fd23eeba13
Create Date: 2026-02-27 02:02:02.087105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11b232c80aca'
down_revision: Union[str, Sequence[str], None] = '36fd23eeba13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shops', sa.Column('hashed_pin', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shops', 'hashed_pin')
    # ### end Alembic commands ###
