"""add product categories and product ownership

Revision ID: 217f1b975253
Revises: 61f113a46e54
Create Date: 2026-03-14 21:36:51.438369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '217f1b975253'
down_revision: Union[str, Sequence[str], None] = '61f113a46e54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_categories_id'), 'product_categories', ['id'], unique=False)
    op.create_index(op.f('ix_product_categories_name'), 'product_categories', ['name'], unique=True)
    op.create_table('product_category_link',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'category_id')
    )
    op.add_column('products', sa.Column('merchant_id', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True))
    op.add_column('products', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('products', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))

    # Backfill: assign existing products to the first merchant user (or user id=1)
    op.execute("UPDATE products SET merchant_id = (SELECT id FROM users WHERE role = 'merchant' LIMIT 1) WHERE merchant_id IS NULL")
    # Now make it NOT NULL
    op.alter_column('products', 'merchant_id', nullable=False)

    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.create_foreign_key(None, 'products', 'users', ['merchant_id'], ['id'])
    op.drop_column('products', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.drop_column('products', 'updated_at')
    op.drop_column('products', 'created_at')
    op.drop_column('products', 'is_deleted')
    op.drop_column('products', 'merchant_id')
    op.drop_table('product_category_link')
    op.drop_index(op.f('ix_product_categories_name'), table_name='product_categories')
    op.drop_index(op.f('ix_product_categories_id'), table_name='product_categories')
    op.drop_table('product_categories')
    # ### end Alembic commands ###
