"""rename product merchant_id to created_by_id

Revision ID: 21b545e52440
Revises: 376d7dbaf980
Create Date: 2026-03-29 01:40:25.966840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21b545e52440'
down_revision: Union[str, Sequence[str], None] = '376d7dbaf980'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'merchant_id', new_column_name='created_by_id')
    op.drop_constraint('products_merchant_id_fkey', 'products', type_='foreignkey')
    op.create_foreign_key('products_created_by_id_fkey', 'products', 'users', ['created_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('products_created_by_id_fkey', 'products', type_='foreignkey')
    op.create_foreign_key('products_merchant_id_fkey', 'products', 'users', ['merchant_id'], ['id'])
    op.alter_column('products', 'created_by_id', new_column_name='merchant_id')
    # ### end Alembic commands ###
