"""add shop_product_categories link table

Revision ID: 376d7dbaf980
Revises: 88de97c6f784
Create Date: 2026-03-29 01:14:20.593994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '376d7dbaf980'
down_revision: Union[str, Sequence[str], None] = '88de97c6f784'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_product_categories',
    sa.Column('shop_id', sa.UUID(), nullable=False),
    sa.Column('product_category_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['product_category_id'], ['product_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('shop_id', 'product_category_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shop_product_categories')
    # ### end Alembic commands ###
