"""Add ShopCategory

Revision ID: 61f113a46e54
Revises: 82a7def5a1e3
Create Date: 2026-03-12 05:58:18.891898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61f113a46e54'
down_revision: Union[str, Sequence[str], None] = '82a7def5a1e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_categories_name'), 'shop_categories', ['name'], unique=True)
    op.add_column('shops', sa.Column('category_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'shops', 'shop_categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shops', type_='foreignkey')
    op.drop_column('shops', 'category_id')
    op.drop_index(op.f('ix_shop_categories_name'), table_name='shop_categories')
    op.drop_table('shop_categories')
    # ### end Alembic commands ###
