"""Add order_number to orders

Revision ID: 6e1e897dea12
Revises: 7aaeb930c447
Create Date: 2026-03-22 20:04:03.322019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e1e897dea12'
down_revision: Union[str, Sequence[str], None] = '7aaeb930c447'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('order_number', sa.Integer(), sa.Identity(always=False, start=100000, cycle=False), nullable=False))
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.drop_column('orders', 'order_number')
    # ### end Alembic commands ###
