"""add pre_order fields to orders

Revision ID: 7ea804cba73a
Revises: 37fb97fb287b
Create Date: 2026-02-26 01:09:58.606133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ea804cba73a'
down_revision: Union[str, Sequence[str], None] = '37fb97fb287b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('order_type', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('scheduled_pickup_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('estimated_preparation_minutes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'estimated_preparation_minutes')
    op.drop_column('orders', 'scheduled_pickup_time')
    op.drop_column('orders', 'order_type')
    # ### end Alembic commands ###
