"""Allow duplicate phone per role

Revision ID: 82a7def5a1e3
Revises: 00c683dbac3d
Create Date: 2026-03-01 02:31:15.246677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82a7def5a1e3'
down_revision: Union[str, Sequence[str], None] = '00c683dbac3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=False)
    op.create_unique_constraint('uq_user_email_role', 'users', ['email', 'role'])
    op.create_unique_constraint('uq_user_phone_role', 'users', ['phone_number', 'role'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_phone_role', 'users', type_='unique')
    op.drop_constraint('uq_user_email_role', 'users', type_='unique')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###
