"""add product_requests table

Revision ID: 88de97c6f784
Revises: c91a638b0fc4
Create Date: 2026-03-28 23:26:39.431029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88de97c6f784'
down_revision: Union[str, Sequence[str], None] = 'c91a638b0fc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_user_id', sa.UUID(), nullable=False),
    sa.Column('shop_id', sa.UUID(), nullable=False),
    sa.Column('requested_name', sa.String(), nullable=False),
    sa.Column('requested_image_url', sa.String(), nullable=True),
    sa.Column('requested_price', sa.Float(), nullable=False),
    sa.Column('requested_stock', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['merchant_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_requests_id'), 'product_requests', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_requests_id'), table_name='product_requests')
    op.drop_table('product_requests')
    # ### end Alembic commands ###
