"""Add in_stock to inventory

Revision ID: 8f55da1ae5c1
Revises: 6e1e897dea12
Create Date: 2026-03-25 00:27:15.806711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f55da1ae5c1'
down_revision: Union[str, Sequence[str], None] = '6e1e897dea12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
