"""add product subcategories

Revision ID: 9225f8a307d9
Revises: 80e163392355
Create Date: 2026-03-21 13:39:47.477483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9225f8a307d9'
down_revision: Union[str, Sequence[str], None] = '80e163392355'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_subcategories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_subcategories_id'), 'product_subcategories', ['id'], unique=False)
    op.create_index(op.f('ix_product_subcategories_name'), 'product_subcategories', ['name'], unique=False)
    op.add_column('products', sa.Column('subcategory_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'products', 'product_subcategories', ['subcategory_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'subcategory_id')
    op.drop_index(op.f('ix_product_subcategories_name'), table_name='product_subcategories')
    op.drop_index(op.f('ix_product_subcategories_id'), table_name='product_subcategories')
    op.drop_table('product_subcategories')
    # ### end Alembic commands ###
