"""add product_requests table and shop_category_product_category_link

Revision ID: c91a638b0fc4
Revises: 8f55da1ae5c1
Create Date: 2026-03-28 23:26:07.769954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c91a638b0fc4'
down_revision: Union[str, Sequence[str], None] = '8f55da1ae5c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_category_product_category_link',
    sa.Column('shop_category_id', sa.UUID(), nullable=False),
    sa.Column('product_category_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['product_category_id'], ['product_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shop_category_id'], ['shop_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('shop_category_id', 'product_category_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shop_category_product_category_link')
    # ### end Alembic commands ###
