"""Add progressive onboarding fields to User model

Revision ID: f1670ce23c6f
Revises: 21b47b3aa695
Create Date: 2026-02-27 18:22:46.132211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1670ce23c6f'
down_revision: Union[str, Sequence[str], None] = '21b47b3aa695'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('hashed_pin', sa.String(), nullable=True))
    user_onboarding_step_enum = sa.Enum('REGISTERED', 'VERIFIED', 'PIN_SET', 'COMPLETED', name='user_onboarding_step_enum')
    user_onboarding_step_enum.create(op.get_bind())
    
    op.add_column('users', sa.Column('onboarding_step', user_onboarding_step_enum, nullable=False))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'onboarding_step')
    op.drop_column('users', 'hashed_pin')
    op.drop_column('users', 'is_verified')
    
    user_onboarding_step_enum = sa.Enum('REGISTERED', 'VERIFIED', 'PIN_SET', 'COMPLETED', name='user_onboarding_step_enum')
    user_onboarding_step_enum.drop(op.get_bind())
    # ### end Alembic commands ###
